spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/db_dc
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC#ZIZ0vdjV6HBQEGKi3FNIy9gYfs4GvaGBxHYj8MZfkC0ZtSFdGOUmgBOAT8y6uHYD
    password: ENC#ktHZOyAxa09PASaXGnaWhEbn9VPaz8hs2T8TAHTZrHKn6HE1nxaxzlLhREqS3bvm
server:
  port: 8081
