spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/db_dc
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: developer-community
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1GB
  cache:
    type: caffeine
server:
  port: 8081
springfox:
  documentation:
    swagger-ui:
      enabled: false
mybatis:
  base-packages: com.tuituidan.openhub.mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuituidan.openhub.pojo.entity
dictionary:
  type: xlsx
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minio
  secret-key: minio@123
  bucket: dcstore
